# Generated by Django 3.0.3 on 2020-03-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200309_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lname',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=200),
        ),
    ]
