# Generated by Django 3.0.3 on 2020-03-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='article.jpg', upload_to='article_pics'),
        ),
    ]
