# Generated by Django 3.0.3 on 2020-03-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200309_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='citation',
            field=models.TextField(default=''),
        ),
    ]
